# Window Rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = float,class:confirm
windowrule = float,class:dialog
windowrule = float,class:download
windowrule = float,class:notification
windowrule = float,class:error
windowrule = float,class:splash
windowrule = float,class:confirmreset
windowrule = float,title:Open File
windowrule = float,title:Open files
windowrule = float,title:Save As
windowrule = float,title:branchdialog
windowrule = float,class:Lxappearance
windowrule = float,class:Rofi
windowrule = animation none,class:Rofi
windowrule = float,class:pavucontrol-qt
windowrule = float,class:pavucontrol
windowrule = fullscreen,class:wlogout
windowrule = float,title:wlogout
windowrule = fullscreen,title:wlogout
windowrule = idleinhibit focus,class:mpv
windowrule = idleinhibit fullscreen,class:firefox

windowrule = tile,class:^(Microsoft-edge)$
windowrule = tile,class:^(Brave-browser)$
windowrule = tile,class:^(Chromium)$
windowrule = float,class:^(pavucontrol)$
windowrule = float,class:^(nm-connection-editor)$

# clipse
# ensure you have a floating window class set if you want this behavior
windowrule = float,class:(me.gdmsl.clipse)
# set the size of the window as necessary
windowrule = size 622 652,class:(me.gdmsl.clipse)
windowrule = stayfocused,class:(me.gdmsl.clipse)

# vim: ft=conf
