#!/bin/sh
#
# AUTHOR: Guido Masella <guido.masella@gmail.com>
#

# compose the i3 configuration file
[[ -f ~/.config/i3/config.base ]] && \
    [[ -f ~/.config/i3/config.$HOSTNAME ]] && \
    [[ -f ~/.config/i3/config.theme ]] && \
    cat ~/.i3/config.$HOSTNAME > ~/.config/i3/config && \
    cat ~/.i3/config.base >> ~/.config/i3/config && \
    cat ~/.i3/config.theme >> ~/.config/i3/config
