#!/bin/sh
#
# AUTHOR: Guido Masella <guido.masella@gmail.com>
#

# compose the i3 configuration file
[[ -f ~/.i3/config.base ]] && [[ -f ~/.i3/config.$HOSTNAME ]] && \
    [[ -f ~/.i3/config.colors ]] && \
    cat ~/.i3/config.colors > ~/.i3/config && \
    cat ~/.i3/config.$HOSTNAME >> ~/.i3/config && \
    cat ~/.i3/config.base >> ~/.i3/config

# copy the i3 configuration to sway
[[ -f ~/.i3/config ]] && cp ~/.i3/config ~/.config/sway/config

[[ -f ~/.config/sway/swayadd ]] &&\
    cat ~/.config/sway/swayadd >> ~/.config/sway/config
