preload = ~/Pictures/Wallpapers/lpq6o2autx761.jpg
preload = ~/Pictures/Wallpapers/vo3zefs9rlo61.jpg
preload = ~/Pictures/Wallpapers/dbado5/Post33_jpeg/11.jpg
preload = ~/Pictures/Wallpapers/Personal/gloria_cigoland.jpg
wallpaper = eDP-1,~/Pictures/Wallpapers/Personal/gloria_cigoland.jpg
wallpaper = HDMI-A-1,~/Pictures/Wallpapers/dbado5/Post33_jpeg/11.jpg
wallpaper = DP-2,~/Pictures/Wallpapers/dbado5/Post33_jpeg/11.jpg
wallpaper = DP-1,~/Pictures/Wallpapers/dbado5/Post33_jpeg/11.jpg
