# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  hardware.nix — Hardware-specific configuration for yara (ThinkPad E14)    ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# This file was initially generated by `nixos-generate-config` which probes
# your hardware and writes the results. It defines:
#   - Boot loader settings
#   - Disk encryption (LUKS)
#   - Filesystems and swap
#   - Kernel modules needed for your hardware
#
# You normally don't edit this much — it's the "hardware facts" of your machine.
#
# The function signature `{ config, lib, pkgs, modulesPath, ... }:` means this
# file is a Nix *module* — a function that receives the NixOS module system's
# arguments and returns an attribute set of configuration options.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    # Pulls in NixOS's hardware detection fallbacks (e.g., for firmware loading)
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ── Boot loader ─────────────────────────────────────────────────────────
  # systemd-boot is a simple UEFI boot manager (alternative to GRUB).
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Kernel modules loaded in the initrd (the minimal filesystem used during
  # early boot, before the real root is mounted). These drivers let the kernel
  # talk to your NVMe SSD, USB ports, and Thunderbolt dock.
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # kvm-amd enables hardware virtualization for VMs on AMD CPUs
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # ── LUKS full-disk encryption ───────────────────────────────────────────
  # LUKS (Linux Unified Key Setup) encrypts the root partition. During boot,
  # you're prompted for a passphrase to unlock it. The UUID identifies the
  # physical partition (persists even if /dev/sdX names change).
  boot.initrd.luks.devices."luks-d970544f-bfd2-4e62-9f87-395e7d1bc246".device =
    "/dev/disk/by-uuid/d970544f-bfd2-4e62-9f87-395e7d1bc246";

  # Root filesystem (the decrypted LUKS volume, mounted as /)
  fileSystems."/" = {
    device = "/dev/mapper/luks-d970544f-bfd2-4e62-9f87-395e7d1bc246";
    fsType = "ext4";
  };

  # EFI System Partition (ESP) — holds the boot loader, unencrypted
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E5A9-16C5";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];  # restrict permissions
  };

  # ── Encrypted swap (for hibernate) ──────────────────────────────────────
  # Swap is also encrypted (otherwise your RAM contents leak to disk during
  # hibernate). `resumeDevice` tells the kernel where to look for the
  # hibernation image on resume.
  boot.initrd.luks.devices."luks-88d3d5fd-fdfc-4b31-9ea6-b993af4e8b7f".device =
    "/dev/disk/by-uuid/88d3d5fd-fdfc-4b31-9ea6-b993af4e8b7f";
  boot.resumeDevice = "/dev/mapper/luks-88d3d5fd-fdfc-4b31-9ea6-b993af4e8b7f";

  swapDevices = [
    { device = "/dev/mapper/luks-88d3d5fd-fdfc-4b31-9ea6-b993af4e8b7f"; }
  ];

  # ── Firmware & CPU ──────────────────────────────────────────────────────
  # Loads proprietary firmware blobs for Wi-Fi, Bluetooth, GPU, etc.
  hardware.enableRedistributableFirmware = true;

  # mkDefault means "use this value unless something else sets it with higher
  # priority." This is a gentle default that other modules can override.
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
