# Hardware configuration for yara (ThinkPad E14 Gen 7)
# Generated by nixos-generate-config, with boot loader added
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # LUKS encrypted root
  boot.initrd.luks.devices."luks-d970544f-bfd2-4e62-9f87-395e7d1bc246".device =
    "/dev/disk/by-uuid/d970544f-bfd2-4e62-9f87-395e7d1bc246";

  fileSystems."/" = {
    device = "/dev/mapper/luks-d970544f-bfd2-4e62-9f87-395e7d1bc246";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E5A9-16C5";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # LUKS encrypted swap
  swapDevices = [
    { device = "/dev/mapper/luks-88d3d5fd-fdfc-4b31-9ea6-b993af4e8b7f"; }
  ];

  # CPU
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
