# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  hardware.nix — Hardware-specific configuration for yara (ThinkPad E14)    ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# Boot loader, disk encryption, filesystems, swap and the kernel modules this
# machine needs. Originally generated by `nixos-generate-config`, and rarely
# worth editing — it's a description of the hardware.
#
# system/default.nix holds everything that isn't specific to this laptop.
# The equivalent file for the portable SSD is system/nomad.nix.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    # NixOS fallbacks for hardware that wasn't detected.
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  networking.hostName = "yara";

  # ── Boot loader ─────────────────────────────────────────────────────────
  # UEFI-only, which is fine for a fixed machine. The portable SSD uses GRUB
  # instead, since it has to boot on hardware it hasn't seen.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Drivers available in the initrd — the small root used during early boot,
  # before the real one is mounted. These cover the NVMe disk, USB and the dock.
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # Hardware virtualisation for VMs.
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # ── Disk encryption ─────────────────────────────────────────────────────
  # The root partition is encrypted; boot prompts for the passphrase. Referred
  # to by UUID, which stays put even when /dev/sdX names change.
  boot.initrd.luks.devices."luks-d970544f-bfd2-4e62-9f87-395e7d1bc246".device =
    "/dev/disk/by-uuid/d970544f-bfd2-4e62-9f87-395e7d1bc246";

  # The decrypted volume.
  fileSystems."/" = {
    device = "/dev/mapper/luks-d970544f-bfd2-4e62-9f87-395e7d1bc246";
    fsType = "ext4";
  };

  # Holds the boot loader. Can't be encrypted — firmware has to read it.
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E5A9-16C5";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];  # restrict permissions
  };

  # ── Swap ────────────────────────────────────────────────────────────────
  # Encrypted too, or hibernating would write memory contents to disk in the
  # clear. resumeDevice is where the kernel looks for the hibernation image.
  boot.initrd.luks.devices."luks-88d3d5fd-fdfc-4b31-9ea6-b993af4e8b7f".device =
    "/dev/disk/by-uuid/88d3d5fd-fdfc-4b31-9ea6-b993af4e8b7f";
  boot.resumeDevice = "/dev/mapper/luks-88d3d5fd-fdfc-4b31-9ea6-b993af4e8b7f";

  swapDevices = [
    { device = "/dev/mapper/luks-88d3d5fd-fdfc-4b31-9ea6-b993af4e8b7f"; }
  ];

  # ── Firmware & CPU ──────────────────────────────────────────────────────
  # Wi-Fi, Bluetooth and GPU firmware.
  hardware.enableRedistributableFirmware = true;

  # mkDefault sets a value another module can override without needing
  # mkForce.
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
