#
# i3 colors and theming
#
# vim: set ft=conf sw=4 ts=4 sts=4 et tw=78 fdm=marker fdl=0 foldmarker={{{,}}} :

## Base16 Nord
# Author: arcticicestudio
#
# You can use these variables anywhere in the i3 configuration file.

set $base00 #2E3440
set $base01 #3B4252
set $base02 #434C5E
set $base03 #4C566A
set $base04 #D8DEE9
set $base05 #E5E9F0
set $base06 #ECEFF4
set $base07 #8FBCBB
set $base08 #BF616A
set $base09 #D08770
set $base0A #EBCB8B
set $base0B #A3BE8C
set $base0C #88C0D0
set $base0D #81A1C1
set $base0E #B48EAD
set $base0F #5E81AC

# Basic color configuration using the Base16 variables for windows and borders.
# Property Name         Border  BG      Text    Indicator Child Border
client.focused          $base05 $base0D $base00 $base0D $base0C
client.focused_inactive $base01 $base01 $base05 $base03 $base01
client.unfocused        $base01 $base00 $base05 $base01 $base01
client.urgent           $base08 $base08 $base00 $base08 $base08
client.placeholder      $base00 $base00 $base05 $base00 $base00
client.background       $base07
